controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    hebi_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

forward_position_controller:
  ros__parameters:
    joints:
      # - wheel_1
      # - wheel_2
      # - wheel_3
      - arm/J1_base
      - arm/J2_shoulder
      - arm/J3_elbow
      - arm/J4_wrist1
      - arm/J5_wrist2
    interface_name: position

hebi_arm_controller:
  ros__parameters:
    joints:
      # - wheel_1
      # - wheel_2
      # - wheel_3
      - arm/J1_base
      - arm/J2_shoulder
      - arm/J3_elbow
      - arm/J4_wrist1
      - arm/J5_wrist2
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity